### ISSUE TITLE
How to use in Swift 3?

### ISSUE THREAD

**Issue by sirvon** [SolsmaHawk/SDLoopingVideoBackgroundView#1]
Thanks for this. 

Many, many crucial and interesting uses.

How can I bring this feature into a swift code base briskly?

Thanks!

**Comment by SolsmaHawk** [comment]
You can create a bridging header to call this class from your Swift code. A good example of how to do this is here: 

[http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift](url)

Basically, you create a header file named `YourProjectName-Bridging-Header.h` and then you import SDLoopingVideoBackgroundView into that bridging header `#import "SDLoopingVideoBackgroundView.h"` 

Then to instantiate the class from your swift file, do something like this:
`let loopingVideoNode: SDLoopingVideoBackgroundView = SDLoopingVideoBackgroundView(frame: self.view.frame, withPathToResource: "sampleVid", withFiletype: "mp4")
        self.view.addSubview(loopingVideoNode)`

I will probably be adding an example swift project at sometime in the future.
